#!/usr/bin/env ruby

###############################
#Definicion del Main del Lexer#
###############################
require './Lexer'

def main

  input = File::read(ARGV[0]) #Lectura de entrada en un string
  lexer = Brainiac::Lexer::new(input) #Creacion de un lexer
  goon = true

  while (goon) do
    goon = lexer.lex_catch #Se van racogiendo la palabras hasta que diga false
  end
  lexer.to_s #Salida por pantalla como se especifico
end

main
